/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/6ea33e03-e853-4af0-b613-43d38857ed6e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String comando;
  int dadosGrafico;
  bool btnServo;
  bool chovendo;
  bool statusJanela;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>
#define PINO_SERVO D5
#define PINO_SENSOR D7
Servo servo;

void setup() {
  pinMode(PINO_SENSOR, INPUT);
  servo.attach(PINO_SERVO);
  servo.write(0);
  Serial.begin(9600);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  if (digitalRead(PINO_SENSOR) == LOW) {
    chovendo = true;
    fecharJanela();
  } else {
    chovendo = false;
  }
  dadosGrafico = analogRead(PINO_SENSOR);
}


/*
  Since Chovendo is READ_WRITE variable, onChovendoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onChovendoChange()  {
  if(chovendo == true){
    fecharJanela();
  }
}

/*
  Since BtnServo is READ_WRITE variable, onBtnServoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBtnServoChange()  {
  if(btnServo == true){
    fecharJanela();
  } else {
    abrirJanela();
  }
}

void abrirJanela(){
  servo.write(0);
  statusJanela = false;
}

void fecharJanela(){
  servo.write(180);
  statusJanela = true;
} 

/*
  Since Comando is READ_WRITE variable, onComandoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onComandoChange()  {
  Serial.println("Insira seu comando: 'Fechar' ou 'Abrir'");
  if (comando == "Abrir" || comando == "abrir" || comando == "ABRIR") {
    abrirJanela();
  } else if (comando == "Fechar" || comando == "fechar" || comando == "FECHAR") {
      fecharJanela();
  }
}

/*
  Since DadosGrafico is READ_WRITE variable, onDadosGraficoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDadosGraficoChange()  {
  // Add your code here to act upon DadosGrafico change
}

/*
  Since StatusJanela is READ_WRITE variable, onStatusJanelaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStatusJanelaChange()  {
  // Add your code here to act upon StatusJanela change
}
